#!/bin/bash

g++ -stdlib=libstdc++ src/main.cpp src/objtexturehelper.cpp src/modelUtils.cpp src/skpmodel.cpp src/geomutils.cpp -o build/skp2obj -Iinclude/ -framework slapi
#g++ -stdlib=libstdc++ src/main.cpp src/objtexturehelper.cpp -o build/skp2obj -Iinclude/




